### ISSUE TITLE
Crash 1.20.1: Ticking entity

### ISSUE THREAD

**Issue by tr1kright** [davidjjung/just_dandy#10]
Crash Report: https://gist.github.com/tr1kright/4bee7ae7a9e0eea509f79958d5bd756c
Latest Log: https://gist.github.com/tr1kright/716ccfff4d42a698a4dc715556ff53e7

When I use the brush, the game crashes.

**Comment by davidjjung** [comment]
yeah..i have no idea where the issue comes from tbh. usually compat plays nice, but i guess not in this case. i'll implement a more robust solution eventually that implements another block tag, but this will do for now. cheers

**Comment by aurora-hope** [comment]
Unfortunately, the ticking entity crash when missing World of Wonder is happening again on 2.1.5. Downgrading to 2.1.4 fixes the issue.

**Comment by davidjjung** [comment]
fixed with an obvious solution that i had totally forgotten to implement for some reason! hopefully nothing of that sort should crop up again
