### ISSUE TITLE
java.lang.NullPointerException in animateTick

### ISSUE THREAD

**Issue by alairack** [davidjjung/just_dandy#3]
When I play on the server, an error occurs.
Below is my environment:

forge-1.16.5-36.2.39.jar
Just Dandy 1.16.5-1.0.1 

Here is the log summary：
at com.davigj.just_dandy.common.block.FluffyDandelionFlowerBlock.func_180655_c(FluffyDandelionFlowerBlock.java:36) ~[just_dandy:1.0.1] {re:mixin,re:classloading}

Here is the full log:
[just dandy log.txt](https://github.com/davidjjung/just_dandy/files/10887332/just.dandy.log.txt)

**Comment by alairack** [comment]
I think "worldIn.getBiome(pos).getRegistryName()" return NULL
![image](https://user-images.githubusercontent.com/58844478/222872530-4985a1ec-5e76-4f1e-91d3-f9c5d7c2b548.png)

**Comment by KeVrX** [comment]
A really similar issue occurred while I was playing a Modpack with a friend.
Here is my environment:
Minecraft-1.16.5-rc1
Forge-36.2.39
Java-JDK 11.0.12 64bit **OR** JDK 16.0.2 64bit
In addition, Optifine is also used in the Modpack and its version is G8.

The problem overview is that the game of non-host players will crash after being online for a period of time, but the host will not have any problems.
At present, we can basically determine that this mod is the very one which caused the problem. So I'm here to submit the relevant log file so that you may solve the problem and improve the mod.

Here is the log summary:
java.lang.NullPointerException: Cannot invoke "net.minecraft.util.ResourceLocation.toString()" because the return value of "net.minecraft.world.biome.Biome.getRegistryName()" is null

And here is the intact log pointing to the entire Modpack:
[crash-2023-03-06_15.33.45-client.txt](https://github.com/davidjjung/just_dandy/files/10897478/crash-2023-03-06_15.33.45-client.txt)

**Comment by alairack** [comment]
> A really similar issue occurred while I was playing a Modpack with a friend. Here is my environment: Minecraft-1.16.5-rc1 Forge-36.2.39 Java-JDK 11.0.12 64bit **OR** JDK 16.0.2 64bit In addition, Optifine is also used in the Modpack and its version is G8.
> 
> The problem overview is that the game of non-host players will crash after being online for a period of time, but the host will not have any problems. At present, we can basically determine that this mod is the very one which caused the problem. So I'm here to submit the relevant log file so that you may solve the problem and improve the mod.
> 
> Here is the log summary: java.lang.NullPointerException: Cannot invoke "net.minecraft.util.ResourceLocation.toString()" because the return value of "net.minecraft.world.biome.Biome.getRegistryName()" is null
> 
> And here is the intact log pointing to the entire Modpack: [crash-2023-03-06_15.33.45-client.txt](https://github.com/davidjjung/just_dandy/files/10897478/crash-2023-03-06_15.33.45-client.txt)

Our problem is similar, and should only be seen in multiplayer games

**Comment by alairack** [comment]
> > > 当我和朋友一起玩 Modpack 时，发生了一个非常相似的问题。这是我的环境： Minecraft-1.16.5-rc1 Forge-36.2.39 Java-JDK 11.0.12 64bit **OR** JDK 16.0.2 64bit 另外，Modpack中也使用了Optifine，版本为G8。
> > > 问题概况是非主机玩家上线一段时间后游戏会崩溃，但主机不会有任何问题。目前我们基本可以确定是这个mod引起了问题。所以我在这里提交相关日志文件，以便您解决问题并改进mod。
> > > 这是日志摘要：java.lang.NullPointerException：无法调用“net.minecraft.util.ResourceLocation.toString()”，因为“net.minecraft.world.biome.Biome.getRegistryName()”的返回值为 null
> > > 并且这是指向整个 Modpack 的完整日志：[crash-2023-03-06_15.33.45-client.txt](https://github.com/davidjjung/just_dandy/files/10897478/crash-2023-03-06_15.33.45-client.txt)
> > 
> > 
> > 我们的问题类似，应该只出现在多人游戏中
> 
> 的确。并且崩溃只发生在非主机玩家的游戏中。

Unfortunately, the author no longer seems to care about the project

**Comment by alairack** [comment]
> > > A really similar issue occurred while I was playing a Modpack with a friend. Here is my environment: Minecraft-1.16.5-rc1 Forge-36.2.39 Java-JDK 11.0.12 64bit **OR** JDK 16.0.2 64bit In addition, Optifine is also used in the Modpack and its version is G8.
> > > The problem overview is that the game of non-host players will crash after being online for a period of time, but the host will not have any problems. At present, we can basically determine that this mod is the very one which caused the problem. So I'm here to submit the relevant log file so that you may solve the problem and improve the mod.
> > > Here is the log summary: java.lang.NullPointerException: Cannot invoke "net.minecraft.util.ResourceLocation.toString()" because the return value of "net.minecraft.world.biome.Biome.getRegistryName()" is null
> > > And here is the intact log pointing to the entire Modpack: [crash-2023-03-06_15.33.45-client.txt](https://github.com/davidjjung/just_dandy/files/10897478/crash-2023-03-06_15.33.45-client.txt)
> > 
> > 
> > Our problem is similar, and should only be seen in multiplayer games
> 
> Indeed. And crashes only happen in the non-host players' game.

Unfortunately, the author no longer seems to care about the project

**Comment by davidjjung** [comment]
Hello,

Huge apologies for the delayed response!! Unfortunately, I will not be supporting 1.16.5 any further (and I've just updated the CF website to reflect this). There's a 1.19.2 port coming out soon, in case that appeals to either of you--I just submitted it for review on Modrinth. Sorry again for the inconvenience!
