### ISSUE TITLE
Forge 1.20.1 Crash

### ISSUE THREAD

**Issue by spunchbop121** [davidjjung/just_dandy#8]
https://mclo.gs/EjZ7KEu

Game crashes when placing Supplementaries' bellows block or placing dandelion flower right in front of the bellow block.

**Comment by davidjjung** [comment]
Oops, thanks for reminding me. That error actually has nothing to do with Supp, it's just because I moved a few classes around in World of Wonder for 1.1.10 and forgot to update compat here. Thanks for the reminder! Gimme just a second please
